databases:
  - name: task_DB
    databaseName: task_db_kguv
    user: task_manager
    region: singapore

services:
  - type: web
    name: task_manager
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

